### ISSUE TITLE
HExit does not evaluate middleware

### ISSUE THREAD

**Issue by ex0ns** [zio/zio-http#1076]
**Describe the bug**

I was trying to test my middleware in https://github.com/dream11/zio-http/pull/923/files by extending `HExitAssertion`.
When using the `@@ middleware` I always got the following error:
```
`res` = Effect(<function1>) did not satisfy isSuccess()
```

**To Reproduce**

Steps to reproduce the behaviour:
```scala
test("middleware") {
  val app = Http.collectHttp[Request] { case _ => Http.text("") } @@ updateResponse(identity)
  assert(app.execute(Request()))(equalTo(HExit.succeed(Response.text(""))))
}
```

**Expected behaviour**
It should evaluate the middleware and return the response

**Additional context**
It has been discussed and confirmed with @girdharshubham

**Comment by girdharshubham** [comment]
Thanks for raising this issue, @ex0ns.

execute is supposed to return an `HExit`, which you then use by calling the `toZIO` operator on it. The idiomatic way would be to use the `apply` method that does this for you already. This ensures that a ZIO effect is created only when it is required.

**Comment by tusharmath** [comment]
@ex0ns Thanks for the issue. I think you are coming from a contributor's perspective so I can be a bit more detailed a about why this might not be a bug :)

`HExit` is used as an optimization of sorts. Instead of encoding `Http[R, E, A, B]` as `A => ZIO[R, Option[E], B]` we encode it as `A => HExit[R, E, B]`. This gives us an ability to execute as much as possible without shifting to the ZIO Runtime. That gives us quite a lot of performance gains.

So when an instance of Http needs to be evaluated on the backend, we do it two phases 
1. Evaluate it to `HExit` first, and see if it succeeds, fails or is an effect.
2. If it's an effect, further evaluation is required using ZIO Runtime (Which is what is happening in your case).

All this optimization code is written in `Handler.scala` for you to take a look and understand.

Now considering the usecase you are talking about, since you want to write a unit test, you should almost always use the `apply` method for it. As @girdharshubham said, it's the most idiomatic way of writing tests :)

Feel free to ask more questions and thank you once again for your contribution, I am looking forward to getting your PR merged :)

**Comment by ex0ns** [comment]
That is actually really interesting, thanks for the in depth explanation, I'll have a look at `Handler.scala` to read a bit more about that
