### ISSUE TITLE
Server connection closed by the client causes unhandled interrupt

### ISSUE THREAD

**Issue by guersam** [zio/zio-http#1295]
**Describe the bug**
When the connection is closed by the client, ZIO runtime reports unhandled interrupt even if the response is successful.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run a server
```scala
import zio.*
import zhttp.http.*
import zhttp.service.Server

object ZHttpConnectionCloseSample extends ZIOAppDefault {
  override val bootstrap = Runtime.logRuntime

  val app =
    Http(Response.text("Hello")) @@
      Middleware.addHeader(("connection", "close"))

  def run = Server.start(8089, app)
}
```

2. `$ curl localhost:8089`

**Expected behaviour**
No suspicious log appears

**Screenshots**
```
timestamp=2022-06-07T07:51:02.738881139Z level=INFO thread=#zio-fiber-13 message="Fail Interrupt(Runtime(15,1654588262,zhttp.service.HttpRuntime.closeListener(HttpRuntime.scala:58)),StackTrace(Runtime(14,1654588262,zhttp.service.HttpRuntime.unsafeRun(HttpRuntime.scala:25)),Chunk(zhttp.service.Handler.unsafeRun(Handler.scala:135)))) at zhttp.service.HttpRuntime.unsafeRun(HttpRuntime.scala:31)" location=zhttp.service.HttpRuntime.unsafeRun file=HttpRuntime.scala line=31
```
**Additional context**
zio-http version: 2.0.0-RC9

**Comment by guersam** [comment]
I guess here's the code block causing the log: https://github.com/dream11/zio-http/blob/v2.0.0-RC9/zio-http/src/main/scala/zhttp/service/HttpRuntime.scala#L26-L32

A naive solution is to catch every interrupt and just ignore it, but a distinction might be needed between expected and unexpected connection close which I'm not sure if possible.

@tusharmath What do you think?

**Comment by tusharmath** [comment]
Thanks @guersam ! I tried to reproduce this issue and found that the connection is getting closed by the server as soon as the response is written and not the client.
Since it's an `INFO` level log, I don't think it's really that confusing. I will close this issue for now, and reopen only if we know exactly what to do here.

We need to keep the runtime light weight. Adding more operators such as catchAll and then filter on the cause, will affect the performance of the application dramatically which we should avoid.
