### ISSUE TITLE
Requests run on Netty's thread pool

### ISSUE THREAD

**Issue by gbecan** [zio/zio-http#1368]
**Describe the bug**
Implementations of HTTP requests are executed on Netty's thread pool instead of ZIO default thread pool.

**To Reproduce**
Run this app:
```scala
import zhttp.http.*
import zhttp.service.Server
import zio.*

object CheckThreadPool extends ZIOAppDefault {

  override def run: ZIO[Any, Any, Any] = {
    val app = Http.collectZIO[Request] { 
       case Method.GET -> !! / "thread-pool" => ZIO.attempt(Thread.currentThread().getName).map(Response.text)
    }

    Server.start(8080, app).exitCode
  }
}
```

Go to [localhost:8080/thread-pool](http://localhost:8080/thread-pool)
The page indicates the thread pool used to compute the result of the request.
In my case it displays something like `epollEventLoopGroup-2-3` which corresponds to Netty.

**Expected behaviour**
Implementation of requests should execute on default ZIO thread pool.

**Additional context**
Tested on 2.0.0-RC10 and 1.0.0.0-RC29

**Comment by tusharmath** [comment]
@gbecan This is by design. 
This threading model performs better because there is no context switching
and going forward, the zio http client and other clients such as ZIO Kafka, ZIO Redis, etc.
will also be running on the same thread. 
This will allows developers to write high performance libraries and codecs without worrying about thread safety.

**Comment by guizmaii** [comment]
IIRC, we're not supposed to run application code on Netty's thread pool 🤔

**Comment by gciuloaica** [comment]
@guizmaii I think the recommendation is to: never block or perform computationally intensive operations on Netty's EventLoop.
