### ISSUE TITLE
The tests for a HttpApp don't work as expected

### ISSUE THREAD

**Issue by dylandoamaral** [zio/zio-http#1814]
**Describe the bug**
I tried to test one of my route using zio http with Scala 3 but it doesn't work, I obtain the following error:

```
+ Test simple requests
  - Test simple request
    Exception in thread "zio-fiber-70" scala.None$: None
        at issue.ServerSpec.spec(ServerSpec.scala:16)
        at issue.ServerSpec.spec(ServerSpec.scala:17)
        at issue.ServerSpec.spec(ServerSpec.scala:18)
```

**To Reproduce**
You can clone the following project and run the test:
https://github.com/dylandoamaral/zio-http-issue

One day I will certainly delete the repository so just in case here is the code:

Server.scala
```
package issue

import zio.*
import zio.http.*
import zio.http.model.Method

object Server {
  val app: HttpApp[Any, Nothing] = Http.collect[Request] {
    case Method.GET -> !! / "text" => Response.text("Hello World!")
  }
}
```

ServerSpec.scala
```
package issue

import issue.ServerSpec.{suite, test}
import zio.Scope
import zio.http.{Request, URL}
import zio.test.{Spec, TestEnvironment, ZIOSpecDefault, assertTrue}

object ServerSpec extends ZIOSpecDefault {

  override def spec: Spec[TestEnvironment with Scope, Any] =
    suite("Test simple requests")(
      test("Test simple request") {
        val request = Request.get(URL.root.setPath("text"))

        for {
          response <- Server.app.apply(request)
        } yield assertTrue(response.status.code == 200)
      }
    )
}
```

**Expected behaviour**
The test should succeed.

**Screenshots**
None

**Desktop (please complete the following information):**
OS: Mac OS

**Comment by dylandoamaral** [comment]
The version of zio was 2.0.4, it seems to work with 2.0.2.

**Comment by vigoo** [comment]
Note: the problem is that the path in the request URL is `text` and not `/text`.

That said, I think the URL constructed in the example code should mean the same.

**Comment by vigoo** [comment]
Checked the code a bit more. Here you are constructing a relative URL `"text"` and that is getting matched by the `Http` handler which looks for a request having `GET` method and `!! / "text"` which means `/text` in its path. It is correct that this pattern match is not matching the relative URL in the request. 

In a real-world (non-test) situation the request would contain an absolute URL and would work as intended - the test can be fixed by prefixing the path with `/`. 

So I think this is not a bug.
