### ISSUE TITLE
Refactor model of Http

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-http#1871]
The current model of `Http[R, E, A, B]` is:

```scala
A => ZIO[R, Option[E], A]
```

Unfortunately, this means that a middleware **cannot know if a handler wants to handle a route until it's too late**.

Middleware incoming actions must be run **if and only if** a handler wants to handle a route. But there is no ability to do that, because in order to see if a handler wants to handle a route, it must be invoked with the input. At which point, it's too late.

The current middleware always runs, **every single time**, regardless of whether a handler wants to handle a route, **which is incorrect and leads to numerous issues**.

In order to solve this problem, a handler must be able to indicate **whether or not** it wishes to handle a route, independently of actually handling a route.

Therefore, the model must change to:

```scala
PartialFunction[A, ZIO[R, E, A]]
```

This proposal is **strictly less powerful** than the old model. If this proves to be troublesome, we can split it into a `isDefinedAt: A => ZIO[R, E, Boolean]` and `apply: A => ZIO[R, E, A]` pair. But hopefully that won't be necessary.

**Comment by tusharmath** [comment]
As you said it's strictly less powerful so I won't press on that :) I think this approach will make the Http domain less practical. I think we should keep the Http domain as is and work on other techniques to make it work with endpoints rather than the other way round.

I also feel developers don't always work with endpoints when working with Http.

For eg, while implementing a proxy server, destructuring the request into entities and then rebuilding from scratch can severely impact performance. Instead one would want to pass the received request directly to the downstream service, with some modifications in the request.

Getting a Request as input and responding with a Response is a very intuitive and a good starting point for developers who are working with Http for the first time. In my opinion, this is what people loved the most about ZIO Http, it was easy to start with and there was no boilerplate code that I had to write to define endpoints etc. Advanced users would move to Tapir very quickly if they felt like.

Secondly,
> The current middleware always runs, every single time, regardless of whether a handler wants to handle a route, which is incorrect and leads to numerous issues.

I don't think this is accurate. It depends on the middleware. If the middleware wants to operate on the request, then yes it will run every time before the actual Http. However, if the middleware needs to run on the response of the Http, it will only run if the Http actually produces a response. This is also necessary because middleware should have enough power to switch the control as and when required.

**Comment by vigoo** [comment]
I don’t think the general concept of just getting a request and returning a response would change by this. I’m not finished yet with my refactoring but I think on the Http and Middleware level almost every existing operator can be kept and the only difference would be that in some cases you cannot use a partial http (like collect) but have to provide a fallback or restructure things a little. This reduces the possibilities a bit but on the other hand it makes it possible to know if a particular Http is defined on a given input without executing any side effects, on any level.

I think the changes so far are promising but the linked PR is still draft, I expect it to become cleaner in the end.

Once it’s “done” meaning everything existing is either working or turns out to be not supported by the new encoding we can easier decide how limiting it is compared to the advantages

**Comment by aappddeevv** [comment]
Just to support these concepts I just started using zio-http 0.0.3 and have 3 needs: 1) create a SPA server that servers up SPA-like routes (e.g. mostly map to index.html for most paths), 2) proxy back to a graphql backend like caliban and then 3)  develop a simple (no endpoint declarative overhead desired) or a small set of routes (for a small API that is used internally hence manual route specification is easier).

1) Allows me to avoid overhead of provisioning a cloud based web server e.g. azure static web app or a nginx server in my app container. For small apps, keeping it all in small stack is just easier. 2) Always need an API of some sort. 3) I often have other routing needs e.g. healthchecks, metrics gathering, monitoring, etc or I need to publish a public REST API of some sort since some people don't like graphql API.

So the use case is sometimes highly consolidated to keep the stack simple (no AKS, no multi-resource cloud config) and sometimes more dedicated e.g. dedicated REST/graphql API server. 

So manual route programming, reading some routes from a file or using a code-based endpoint specification can all be use cases that need to be kept simple enough for people to start quickly and evolve in small increments.

**Comment by jdegoes** [comment]
In looking at the type:

```scala
A => ZIO[R, Option[E], A]
```

We can see that a middleware, when implemented as an `Http => Http`, cannot know if a handler wants to handle a route until after it has tried to invoke the handler. 

This means that middleware which want to run BEFORE a handler, but only if a handler commits to handling a route (e.g. authentication), cannot be implemented correctly.

Indeed, people have independently discovered this using `++` and other operators: middleware is running when it should nto be, and middleware failures are causing whole apps to fail simply because the middleware should not have been running (and therefore should not have failed) because a handler did not commit to handling a route.

In my mind, this indicates the current model is not workable: it only allows middleware that runs based on the request itself, not based on a handler's willingness to commit to a route.

So this means we need to change one of two things:

1. We need to change the model of `Http` to provide more feedback to a middleware on whether a given handler wants to commit to a route.
2. OR, we need to change the model of `Middleware` so that it is no longer a function `Http => Http`.

@vigoo is exploring option (1). We could explore option (2), as well, but I am pretty sure it would mean you can't have "local middleware", e.g. `(a @@ b) ++ (c @@ d)` for some operator like `++`. 

In any case, I don't think there are any performance implications of such a change nor any significant change in our ability to make the API simple or to do things like proxying.

**Comment by tusharmath** [comment]
**First**
> This means that middleware which want to run BEFORE a handler, but only if a handler commits to handling a route (e.g. authentication), cannot be implemented correctly.

This is not always necessary. For eg: If you are using a rate-limiting middleware, you might just want to send a 429 status code, even before the routes are matched. So there is a case to be made for both - execute middleware only if the route is matching and execute whether the route matches or not.

**Second**
Very often route matching can be effectful. So a middleware that only runs if the routes match, will still trigger an effectful computation anyways. And in that case, it's not possible to differentiate a route-matching effect from a response-generating effect (sometimes they can be the same effect).

 For eg: 

```scala
val loadFileFromLocal: HttpApp[Any, Nothing] = ...
val loadFileFromS3: HttpApp[Any, Nothing] = ...
val loadFileFromGCP: HttpApp[Any, Nothing] = ...


val staticFileServer = loadFileFromLocal ++ loadFileFromS3 ++ loadFileFromGCP
```
I am trying to load a file from my local directory and if I don't find it there I want to try S3 and then GCP.
The request could have a URL like:
```
http://localhost:8080/assets/blog-1/1-jan-2023/happy-new-year
```
And I am going to look for the complete path in all types of storage, all of which are IO calls.

**Third**
The behavior of `++` with middleware is a bit confusing, but it's not limiting anyway. I think for such use cases, where one wants categorical isolation between application middleware one can use `collectHttp` and have different routes for each app like I have explained here – https://github.com/zio/zio-http/issues/1627#issuecomment-1370522353

**Comment by tusharmath** [comment]
One proposal that I have is —

1. Keep `Http` domain as it is. 
2. Rename `Middleware` to `HttpAspect` this is more in line with ZIO nomenclature but keep the behavior the same. I think better documentation can help here, instead of a redesign.
3. Develop ZIO API independently with support for powerful routing and a new kind of middleware
4. Compile a ZIO API into an Http for execution.

**Comment by jdegoes** [comment]
Let's say my program is working:

```scala
route1 @@ route1Middleware
```

Then separately, I have another working program:


```scala
route2 @@ route2Middleware
```

I think we have seen that users expect to be able to combine their two programs together with `++`, and assuming their routes do not overlap, have exactly the same behavior as before:

```scala
(route1 @@ route1Middleware) ++ (route2 @@ route2Middleware)
```

In fact, this is not what will happen, as although the route 1 handler will only be invoked in the case of route 1 being invoked (and symmetrically for route 2), the route 1 middleware and route 2 middleware will always be invoked. 

Middleware is global, not local, and therefore requires global reasoning, which is much more complicated for humans to do than local reasoning. Indeed, local reasoning is the main reasoning benefit to functional programming.

The fact that we got many independent bug reports is an indication something is wrong here. 

I do not know how to make "local middleware" with HTTP being as powerful as it is. Even if we change existing `Middleware` to `HttpAspect`, I still don't know how to make a new Middleware that can be attached locally to specific `Http`, and executed if and only if its handler is executed, and not otherwise.

Now, maybe we don't need that. Maybe you could use the endpoint machinery, and compile the "whole API" into a single Http, which will effectively allow "local middleware" at different levels. But it seems odd that the foundational data type of ZIO HTTP is not capable of expressing local middleware.

Thinking about this more, I believe that `Http` is really doing double-duty:

1. It functions as a router, allowing specification of which handlers should be invoked for which routes;
2. It functions as a handler, allowing producing output from input.

The first function requires monoidal composition: we need to be able to combine routers together in a way that's associative, with an identity. 

The second function requires arrow and monad composition: a handler, after all, is essentially a function `A => B`, and therefore composes with arrows (sequential piping), as well as monads (sequential composition reading from the same input).

It is possible we may be able to solve the problems by dividing the solution space into two DSLs: one for routing/dispatch/middleware, and one for input/output handling. It is possible that combining these two different domains into the same data type is resulting in some pain.

I think @vigoo is still exploring the space of possible solutions here, and it's my hope we come up with something that simplifies rather than complicates the API for users, and let's us preserve maximum amount of local reasoning, without diminishing performance.

**Comment by vigoo** [comment]
Yes in my first attempt (in the now closed PR) I was trying to apply the idea of making `Http` a partial function and middlewares only applied in case the targeted `Http` is defined at for the input and minimize the changes to the rest of the API - keep as much operators as possible on top of this new model. I think many parts of the first attempt looked good but the `Middleware` type became very ugly and it indicated that it is not the correct design.

Now I'm trying out some new ideas from @jdegoes based on our discussion and the above comment; I will open a new draft PR once it covers everything again; now my focus will more to have a simple user friendly API than to preserve everything as close to the original as is - while trying to preserve the full feature set and performance, of course.

**Comment by soujiro32167** [comment]
Thanks for tracking this guys. I got here after breaking my head over `a ++ (b @@ mid) =\= (b @@ mid) ++ a`. My health endpoint kept getting caught in the tracing middleware 😅
