### ISSUE TITLE
Security issue: XSS in 404 not found page

### ISSUE THREAD

**Issue by frevib** [zio/zio-http#1873]
**Describe the bug**
Cross-site scripting in 404 page

**To Reproduce**
1. go to non-existing page to trigger the 404 page
2. enter some malicious content in the URI part, e.g localhost/`<script>alert("XSS");</script>`

**Expected behaviour**
The page should print "The requested URI "/<script>alert("XSS");</script>" was not found on this server

**Screenshots**
![Screenshot from 2022-12-08 10-21-36](https://user-images.githubusercontent.com/5623111/206409591-e31fa356-8a5e-4e12-b649-429c03dcf2cc.png)

**Desktop (please complete the following information):**
- All OSes
- All browsers

**Solution**
Add output encoding, PR here:  https://github.com/zio/zio-http/pull/1872

**Comment by strelec** [comment]
Hello,

I would like to suggest few alternative solutions. I think that the existing commit (https://github.com/zio/zio-http/commit/4d8ab6b5cd6d85ed42ca39a7c0ad9e222c36959d) only hides the real issue, and does not ensure safety. It is not advisable to roll out your own security solutions, especially with a security bug as critical as this one.

There are three proposals.

1. **Simply return 404 without a body.** It is not a job of a framework to make error outputs pretty, let the developer choose to do that. Moreover, any kind of custom error pages exposes the implementation (zio-http), which is not great.
2. **Return a simple message using text/plain**. This way, any kind of XSS is not possible anymore, as the output is not imterpreted as HTML.
3. **Keep the pretty HTML page, just do not display the path**. It is redundant anyway, since the user can see the path in the location bar. Why say it again, and compromise security.

**Comment by frevib** [comment]
Thanks for your input. The PR actually does fix this issue, see the OWASP spec on HTML entity encoding. Could you explain why it only “hides” the issue, or explain what you by “hide”?

Your points 1,2 and 3 were discussed in the PR, e.g: https://github.com/zio/zio-http/pull/1872#issuecomment-1342556428 and decided was to use current approach: https://github.com/zio/zio-http/pull/1872#issuecomment-1345210184

I agree it’s not advisable to use your own security solutions, but this is very simple output encoding. If this was about cryptography, I would agree. I would argue it is actually good to include your own `security` package with simple security functions.

Then again, not echoing back user input at all makes less room for errors, and possible security issues.

**Comment by frevib** [comment]
Closing as this issue is fixed in https://github.com/zio/zio-http/pull/1872

**Comment by strelec** [comment]
> Then again, not echoing back user input at all makes less room for errors, and possible security issues.

Sooooo...?
