### ISSUE TITLE
Server.install signature change in v0.0.4

### ISSUE THREAD

**Issue by voltmodder** [zio/zio-http#2028]
Hi
Does the signature change of Server install and other methods of Server class are correct in v0.0.4?
in v0.0.3 it was 
  def install[R](
    httpApp: HttpApp[R, Throwable],
    errorCallback: Option[ErrorCallback] = None,
  )
now in v0.0.4 it become 
  def install[R](
    httpApp: App[R],
    errorCallback: Option[ErrorCallback] = None,
  )
where App expands to type App[-R] = HttpApp[R, Response] i.e. we assume that Response goes as error type
in type HttpApp[-R, +Err] = Http[R, Err, Request, Response]

looks like an error for me

**Comment by voltmodder** [comment]
probably type App should be type App[-R] = HttpApp[R, Throwable]

**Comment by vigoo** [comment]
This is by design, and you can get the `0.0.3` behavior by using `Http#withDefaultErrorResponse` 

The idea is that the server does not know anything about your custom error types, the only thing it can do is return a `Response` to the caller. So we have to define the transformation from the error to the error response. Previously there was a default transformation built-in, which you could not overwrite. Now it's in `withDefaultErrorResponse`.
