### ISSUE TITLE
No Http.catchAll in the newest version

### ISSUE THREAD

**Issue by govorov** [zio/zio-http#2070]
Good evening dear team. I'm upgrading my project to ZIO2 and the latest zio-http. In my app I use the approach below to serialise errors to a certain json structure, with error codes etc.:

```
(httpApp @@ cors(corsConfig).catchAll(e => Http.fail(fromError(e)))

def fromError(error: AppError): Response = ???
```

However, this doesn't work anymore with the newest version of the library. The documentation seems to be out of sync, so I can't figure this out myself. I also tried to find some info on how to use `Handler` and what it is, but ended up reading the source code, as there's nothing in the docs. In general, I need to be able to convert `HttpApp[Any, AppError]` to `HttpApp[Any, Nothing]` somehow.

What is the right way of implementing such error handling logic with the current version of zio-http? Thank you.

**Comment by vigoo** [comment]
That's by design, and we will update the documentation once we reach the 1.0.0 release candidates. 

`Http` is just a collection of `Handler`s selected by a route. On `Handler` you have `catchAll` if you need; but if the goal is to handle errors and generate different `Response`s based on that, the recommended way to do that now is to just use typed errors all the way up to the `Http` level (or any level you need), and then just `mapError` that error into a `Response`, having a `Response` in the error channel too. 

That's the type of `App` that you eventually pass to the server:

```scala
type App[-R]           = HttpApp[R, Response]
```

Errors of type `Response` coming from `App` are sent back to the client just as successful responses are.

**Comment by jdegoes** [comment]
Perhaps we can have a method that lifts an operation on a handler to an operation on an Http, something like, `myHttp.foreachHandler(_.catchAll(...))`.

**Comment by govorov** [comment]
Thank you for the quick response! The suggested solution works.
