### ISSUE TITLE
Server serve endpoints type mismatch

### ISSUE THREAD

**Issue by fernanluyano** [zio/zio-http#2205]
**What is not easy to do right now?**
Add endpoints to the server that are not of type `HttpApp[R, Response]`.
When you call `Server.serve(myApp)` and myApp has a signature like
`val basicEndpoints: Http[SomeLayer with SomeOtherLayer, Throwable, Request, Response]` it complains about a type mismatch.

**Comment by fernanluyano** [comment]
Found the reason for the mismatch. It seems to be when attaching middlewares to the endpoints.

**Comment by vigoo** [comment]
This is by design. You have to specify how to turn errors in to responses before you are able to run it as a server. In this case you need to map your `Throwable` errors into `Response`s that the server can send back to the user.

The two simplest options are:
- `basicEndpoints.withDefaultErrorResponses` - it will respond with an `500 Internal Server Error` without any details
- `basicEndpoints.mapError { throwable => ... }` - if you want to customize the response
