### ISSUE TITLE
Contributors guide link is broken

### ISSUE THREAD

**Issue by suyash5053** [zio/zio-http#2361]
**Describe the bug**
The link to the Contributors guide in Readme.md is broken

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '[Contributing](https://github.com/zio/zio-http#contributing)'
2. Click on '[contributor's guide](https://zio.dev/about/contributing).'
3. See the page not found error.

**Expected behavior**
It should have opened to contributing guideline link.

**Screenshots**
![zio error](https://github.com/zio/zio-http/assets/95718084/3359ab57-4378-4fbf-a611-f22cd538e353)

**Comment by hatchling13** [comment]
I found this issue happens to multiple repos of ZIO official libraries  also.
This is because [`zio-sbt`](https://github.com/zio/zio-sbt), plugin used to generate the `README.md` file wasn't versioned up correctly.

As you can see in [`project/plugin.sbt`](https://github.com/zio/zio-http/blob/main/project/plugins.sbt), the version currently used of `zio-sbt` is v0.3.10 but the correct README.md can be generated by v0.4.0.

Although I'm not sure whether to fix this or not since v0.4.0 is tagged 'alpha'.

**Comment by hatchling13** [comment]
[`zio-kafka`](https://github.com/zio/zio-kafka) is using alpha version of v0.4.0, and GitHub Action is automatically versioning up `zio-sbt`. I think this could be applied to others that aren't.

**Comment by varshith257** [comment]
@987Nabil @jdegoes It can be closed now. It's working fine now in latest version
