### ISSUE TITLE
Easy query parameter extraction

### ISSUE THREAD

**Issue by 987Nabil** [zio/zio-http#2492]
**Extracting query parameters is too hard**

```scala
handler { (req: Request) =>
        val perPage = req.url.queryParams.get("perPage").flatMap(_.toIntOption).getOrElse(10)
        req.url.queryParams.get("page").flatMap(_.toIntOption) match
          case Some(page) => ???
          ...
```

**Use context providing HandlerAspects to extract query parameters with ease**

This is basically working code today

```scala
    trait QueryExtractor[Out] {
      def decode(in: QueryParams): Either[Response, Out]
    }

    val int: String => QueryExtractor[Int] =
      name => (in: QueryParams) => in.get(name).flatMap(_.toIntOption).toRight(Response.badRequest)

    def query[Out](queryExtractor: QueryExtractor[Out]): HandlerAspect[Any, Out] =
      HandlerAspect.interceptIncomingHandler[Any, Out](
        Handler.fromFunctionZIO[Request] { req =>
          queryExtractor.decode(req.url.queryParams) match {
            case Left(response) => ZIO.fail(response)
            case Right(out) => ZIO.succeed((req, out))
          }
        }
        )

    Method.GET / "example" -> query(int("page")) -> handler { case (page: Int, req: Request) => ??? }
```

with this basic concept and some helpers and new methods, we could reach a pretty nice syntax. Maybe something like
```scala
Method.GET / "example" ? int("page") & int("perPage").optional -> handler { case (page: Int, perPage: Option[Int], req: Request) => ??? }
```

We could maybe also offer a way to use `QueryCodec` as an extractor, but I would not limit it to the codec.

The same idea could maybe also work to parse bodys. But I would do this in two different PR's.

I would love to impl. this, but for now RFC, especially to @jdegoes @vigoo @adamgfraser

**Comment by mberndt123** [comment]
Hey @987Nabil,

I'm down with the concept of making it easier to parse Query parameters! That said, I can't help noticing that this…
```
    trait QueryExtractor[Out] {
      def decode(in: QueryParams): Either[Response, Out]
    }
```
…is just a Monad with a Reader and an Error effect, and we already have one of those, namely `ZIO[QueryParams, Response, A]`. Reusing `ZIO` for this purpose keeps the API surface small (e. g. no need for `?` and `&` operators and such things) and thus makes the API easier to learn and use. People can apply all the knowledge they already have on how to compose ZIO values, and it works the other way around too: if you learn something about how query extractors work, that's going to apply in many other `ZIO` contexts as well.

As we have discussed elsewhere, you seem to have concerns that using the `ZIO` type may be too abstract for newcomers and believe that adding a new single-purpose abstraction would make it easier for these less experienced developers. And there is some merit to that, it's not obvious at first glance how the `ZIO` type could have anything to do with query parameters. But I nevertheless believe such concerns to be mistaken for two reasons. The first is that such hurdles can be overcome through good documentation. Sure, if you write the “It's just a monoid in the category of endofunctors” style of documentation then that will be of little use to most people. But if you think carefully about common use cases and illustrate how to solve these in the documentation (including useful snippets that people can paste into their source code without thinking too much about it), then I'm convinced that it can be made easy for those who don't want to delve too deeply into `ZIO` just yet. The second reason is that I don't think we should belittle users and instead empower them to climb the ladder of abstraction. Because honestly I think there are very few things in programming that are more enjoyable than those “Wait, you can use it in _that_ way too?” moments that all of us had at one point or another.

Your second concern is that people may want to use ZIO Http with other effect types that don't have an `R` parameter like `Future` or pure functions. To that I would say that pure functions are a fringe use case – the vast majority of endpoints will perform some kind of effect, and for those that don't, `ZIO.succeed` works just fine. Likewise, `ZIO.fromFuture` is a fine solution for `Future`-based code. You argued that some people might want to write ZIO Http applications but not deal with effect systems – but frankly I find this unconvincing. Trying to be all things to all people is never a good idea, and this group of users is better served with something like [Cask](https://com-lihaoyi.github.io/cask/).

**Comment by guizmaii** [comment]
@mberndt123 

> is just a Monad with a Reader and an Error effect, and we already have one of those, namely ZIO[QueryParams, Response, A]. Reusing ZIO for this purpose keeps the API surface small (e. g. no need for ? and & operators and such things) and thus makes the API easier to learn and use. 

My quick 2 cents. 
I don't think we should make the choice of the return type for `QueryExtractor::decode` based on the criteria you describe here but:
 1. based on what it does. 
    If it's always a pure function there is no need for ZIO (Gave a talk on this subject: https://youtu.be/nZAxtQAJaU0?si=Xs7eRUn3_16MAf-x)
 2. based on what we want to allow people to do with this function in their own `QueryExtractor` implementations. 
    If we don't want to allow them to make side effects (as it's probably not needed to call a DB nor make an HTTP request to decode a query param), then we should stay with something like `Either` to constrain the API to give the right amount of power to our users ("Use the less powerful abstraction" principle)
 
 `Validated` (or `Validation`, I don't remember the name in zio-prelude) could make sense tho if we want to accumulate parsing errors
 
 @987Nabil I like your proposal. The syntax your suggesting looks amazing! 🙂

**Comment by mberndt123** [comment]
In my opinion there is no harm in allowing side effects from a query extractor – responding to an HTTP request is by definition a side effect anyway, so you're unlikely to ever call a query extractor from a pure context. Besides, as @jdegoes once said, “Effect Tracking Is Commercially Worthless” anyway ;-)

But if you insist that query extractors must be pure, then there's `ZPure` for that, along with some type aliases to make it easier to use.
I also don't understand what you mean by “based on what it does” – to me, a Monad with a Reader and an Error effect is a pretty clear description of what it does: it takes a `QueryParams` object as input and returns an `A` value or fails with a `Response`.

**Comment by 987Nabil** [comment]
@guizmaii I am not sure about `Validation`. We have currently no direct dependency to zio prelude. And I think we could even realize the error gathering without it. We could just return `String` as error as we do in many places in zio libs, like zio json for example. Then via convention we would just return a bad request with a list of all errors/missing values.
Thinking about this, I might like this more then `Response` in the error channel. As you said, principle of least power.
We might need to have a switch to turn of returning messages at all, in case you might not want to expose things to an attacker or something like that.

@mberndt123 Same argument, that I think we might not want to depend on zio-prelude. In my dream world, zio-http should also be a good entry level experience/lib that can drive the whole ecosystem. A type like `ZPure` with it's 6 type parameters might not help with this.

**Comment by 987Nabil** [comment]
After talking to some ppl and asking actively for feedback, I think we should maybe tackle all request data extraction in the same way. Which means, that I think we should have an API that can handle not only query params, but also headers and body parsing.
This way, one could have syntax like `customerIdFromQuery | customerIdFromHeader`. What would be interesting about this is, that it gets very close to what we have for the Endpoint API. The difference is, that here we need only decoding, where in the Endpoint API we need codes, since we can create clients too.
So far, they only share the way to define routes, but maybe we can reuse the HttpCodec too, to extract stuff.
The thing I am not sure about is, if it is wise to use `Codec` everywhere or if that is too much overhead and users might like to have only `Decoder`s

**Comment by guersam** [comment]
> I think we should maybe tackle all request data extraction in the same way.

Agree on that. 

> The thing I am not sure about is, if it is wise to use Codec everywhere or if that is too much overhead and users might like to have only Decoders

I actually met the decoder-only situation at work. The project uses Tapir, so I had to define fake encoders for those types.

**Comment by mberndt123** [comment]
At the risk of sounding like a broken record: If you just use a `ZIO[Request, Response, A]` for parameter extraction, you don't need to create custom operators like `|`, you just use `orElse` like for any other ZIO. And if you're going to do arbitrary parameter extraction, purity goes out of the window anyway as you're going to be doing things like JWT token verification, which requires access to the current time, which is a side effect.

**Comment by guersam** [comment]
For the first step, I'd like to see [QueryParams#getAs](https://github.com/zio/zio-http/issues/2423) implemented. It seems less controversial and could provide an immediate improvement to developer experience.

**Comment by 987Nabil** [comment]
After talking with @jdegoes I am closing this. There is one way of easiery query extraction that someone is already working on.
But please keep in mind, if you want to have a very high level API where you don't need to do this stuff, please use the endpoint api.
