### ISSUE TITLE
UIO-based handlers produce `Route.Handled`

### ISSUE THREAD

**Issue by mijicd** [zio/zio-http#2580]
**Describe the bug**

Creating routes with UIO-based handlers produces instances of `Route.Handled`, thus making custom error handling via `handleErrorCause` or `handleErrorCauseZIO` impossible (e.g., logging the defects, custom error responses, etc.). 

**To Reproduce**

Here's a minimal reproducer:

```scala
import zio._
import zio.http._

val route = Method.GET / "test" -> handler((req: Request) => ZIO.debug(s"Received $req").as(Response.ok))

println(route)
```

**Expected behaviour**

While the users can mitigate the issue by using one of `Handler`'s constructors and specifying an error type manually, I would expect that `handleErrorCause*` methods are applicable by default, especially since their docs say:

```
Handles all typed errors, as well as all non-recoverable errors, by converting them into responses.
```

**Comment by gipeshka** [comment]
hey all, I've got an interesting problem with this thingie fixed.

So what we're doing is manually handling defects on routes like 

```scala
  routes.handleErrorCauseZIO(handleError)
```

where routes can have an error of type say `Errors`. And the handleError is doing

```scala
  private def handleError(cause: Cause[Throwable]): UIO[Response] =
    cause.squash match {
      case error: Errors => ZIO.succeed(toResponse(error))
      case defect        => ZIO.logErrorCause("Endpoint failure", cause).as(toResponse(internalServerError(defect.getMessage)))
    }
```

When creating a route for these `routes` I created one with no errors, purely `Handler[Env, Nothing, Request, Response]`.

Well the problem arises due to the fact that the route with no Error happens to be `Handled`, and thus `sandbox`ed. This leads to Handler having `Response` on error channel instead of the original error. So the `handleError` part unexpectedly fails because squash fails and I get an error

```
class zio.http.Response cannot be cast to class java.lang.Throwable (zio.http.Response is in unnamed module of loader &#x27;app&#x27;; java.lang.Throwable is in module java.base of loader &#x27;bootstrap&#x27;)
```

For now I was able to fix it by explicitly passing an error like  `Handler[Env, Errors, Request, Response]`. This forces `Unhandled` to be created. However the behaviour is kinda unexpected, as for my routes `handleError` should work with `Cause[Throwable]` 🤔 And also my type spec there lies as no errors might be returned by the handler.
