### ISSUE TITLE
Add access to Env in error handler 

### ISSUE THREAD

**Issue by davidlar** [zio/zio-http#2870]
Hi!

Would it be possible to add support for accessing Env in e.g. 
Routes.handleErrorRequestCauseZIO(f: (Request, Cause[Err]) => ZIO[Any, Nothing, Response]): Route[Env, Nothing]

so it becomes 

Routes.handleErrorRequestCauseZIO(f: (Request, Cause[Err]) => ZIO[Env, Nothing, Response]): Route[Env, Nothing]? 
It would be great to be able to get logged in user, correlation id etc when generating the error message.

Thanks!

**Comment by 987Nabil** [comment]
@jdegoes I tried this and came to have an issue with this definition of Route
```scala
  private final case class Augmented[InEnv, -OutEnv, +Err](
    route: Route[InEnv, Err],
    aspect: Handler[InEnv, Response, Request, Response] => Handler[OutEnv, Response, Request, Response],
  ) extends Route[OutEnv, Err] {
    def location: Trace = route.location

    def routePattern: RoutePattern[_] = route.routePattern

    override def toHandler(implicit ev: Err <:< Response, trace: Trace): Handler[OutEnv, Response, Request, Response] =
      aspect(route.toHandler)

    override def toString() = s"Route.Augmented(${route}, ${aspect})"
  }
```
I think this makes it currently impossible to have the an `Env` added in the `xxxZIO` operators on Route/Routes.
The error transformation can be done, since the `aspect` does not depend on `Err`. It will only be called, when `Err` is already eliminated.
But `aspect` depends on `InEnv`. If I modify `InEnv` via `mapErrorZIO` for example, the aspect can't be applied to the `Routes[InEnv with NewEnv, NewErr]` anymore.

We could restrict `transform`, which is the only way to create an `Augmented` route, to `Route[Any, Err]`. So `aspect` would be `Handler[Any, Response, Request, Response] => Handler[OutEnv, Response, Request, Response]`.

But I am not sure that is a good idea, because then you might need to provide `InEnv` that you never need, since you want to ignore the original handler like `transform(_ => Handler.ok)` for example.

**Comment by jdegoes** [comment]
@987Nabil Have you tried to make `InEnv` contravariant?
