### ISSUE TITLE
Improve consistency in `HeaderExtension.scala`

### ISSUE THREAD

**Issue by tusharmath** [zio/zio-http#442]
Currently, quite a few operators are available on headers, for both `Request` and `Response` via `HeaderExtension`.
The operators are inconsistently named and described. Some operators are just completely missing.

**Comment by vidyasankarv** [comment]
Hi @tusharmath I would like to work on this 
I have put together the header related mehtods in `HeaderExtension` and `Request` and `Response`. 
```scala
trait HeaderExtension {

  def headers: List[Header]

  def addHeaders(headers: List[Header]): A
  def removeHeaders(headers: List[String]): A

  def addHeader(header: Header): A = addHeaders(List(header))
  def removeHeader(name: String): A = removeHeaders(List(name))

  def getHeader(headerName: CharSequence): Option[Header] 
  def getHeaderValue(headerName: CharSequence): Option[String]
  def getHeaderValues(headerName: CharSequence): List[String] 

  def hasHeader(name: CharSequence, value: CharSequence): Boolean 
  def hasHeader(name: CharSequence): Boolean
}

trait Request extends HeaderExtension[Request] { self =>
	def headers: List[Header]

	override def addHeaders(headers: List[Header]): Request
	override def removeHeaders(headers: List[String]): Request
}

case class Response[-R, +E] private (
  status: Status,
  headers: List[Header],
  data: HttpData[R, E],
  private[zhttp] val attribute: HttpAttribute[R, E],
) extends HeaderExtension[Response[R, E]] { self =>

  override def addHeaders(headers: List[Header]): Response[R, E] 
  override def removeHeaders(headers: List[String]): Response[R, E] 

}

```

Could you please elaborate a little more on the changes you have in mind. thank you

**Comment by tusharmath** [comment]
- consistency in terms  of naming
- using string vs char sequence
- sort methods alphabetically
- add scala docs

Some of the things I can think of

**Comment by amitksingh1490** [comment]
This Issue needs to fix the inconsistent naming conventions for Example
In header.scala we have `val transferEncodingChunked` but in HeaderExtension we have a `def setChunkedEncoding` method we need to find out the discrepancies like this and make them consistent

**Comment by vidyasankarv** [comment]
@amitksingh1490 please have a look at this small PR that addressses some of the above issues. https://github.com/dream11/zio-http/pull/453

Regarding the inconsistent use of `String` and `CharSequence`. Is there any preference towards one?

**Comment by kaushik143** [comment]
@vidyasankarv Looks good. Can you work on scala doc also :)

**Comment by amitksingh1490** [comment]
> @amitksingh1490 please have a look at this small PR that addressses some of the above issues. #453
> 
> Regarding the inconsistent use of `String` and `CharSequence`. Is there any preference towards one?

`CharSequence` is preferable

**Comment by vidyasankarv** [comment]
> @vidyasankarv Looks good. Can you work on scala doc also :)
@kaushik143 added scala docs can you please take a look

**Comment by vidyasankarv** [comment]
> > @amitksingh1490 please have a look at this small PR that addressses some of the above issues. #453
> > Regarding the inconsistent use of `String` and `CharSequence`. Is there any preference towards one?
> 
> `CharSequence` is preferable

Hi @amitksingh1490 switching `CharSequence` breaks quite a few methods since they rely on methods on the String, would  it be ok to switch to using String instead ?

**Comment by vidyasankarv** [comment]
> > > @amitksingh1490 please have a look at this small PR that addressses some of the above issues. #453
> > > Regarding the inconsistent use of `String` and `CharSequence`. Is there any preference towards one?
> > 
> > 
> > `CharSequence` is preferable
> 
> Hi @amitksingh1490 switching `CharSequence` breaks quite a few methods since they rely on methods on the String, would it be ok to switch to using String instead ?

Hi @amitksingh1490 It was not possible to switch to `String` because https://github.com/vidyasankarv/zio-http/blob/2a1e7cd94752417a1311eacd7b362827ed8fc509/zio-http/src/main/scala/zhttp/http/Header.scala#L11  
 Header values are built using values like `HeaderNames.CONTENT_TYPE, HttpHeaderValues.TEXT_HTML from `io.netty.handler.codec.http` which is using `AsciiString`. 

So went  back to using `CharSequence` in the `HeaderExtension` which causes a `toString` in a few places where the `String` methods are needed as linked below.

https://github.com/dream11/zio-http/pull/453/commits/420ef86fac56c042435e62310ab43e14de87161d#diff-a8f15f072412b6e70d4687e9a6c64fe12c429aa366ec82cfb5efacdb45204da6R34

https://github.com/dream11/zio-http/pull/453/commits/420ef86fac56c042435e62310ab43e14de87161d#diff-a8f15f072412b6e70d4687e9a6c64fe12c429aa366ec82cfb5efacdb45204da6R52

https://github.com/dream11/zio-http/pull/453/commits/420ef86fac56c042435e62310ab43e14de87161d#diff-a8f15f072412b6e70d4687e9a6c64fe12c429aa366ec82cfb5efacdb45204da6R211

Please have a look. We can revert if you feel otherwise and if you are happy with the other changes, do you think we can merge this ? thank you
