### ISSUE TITLE
Make benchmarks run on forks

### ISSUE THREAD

**Issue by tusharmath** [zio/zio-http#619]
**What is not easy to do right now?**
Currently, it's not possible to run benchmarks on forked repositories

**Describe the solution you'd like**
I would like it if the benchmarks could run on forked repos also.

**Why is this important?**
Contributors might propose changes that can affect performance both in a good or a bad way. At the moment it is impossible to identify the impact of such change.

**Comment by amitksingh1490** [comment]
Due to permission restrictions on running github actions from fork, Any token provided will have only read access, Hence commenting on PR is not possible on forks
Reference: https://github.community/t/github-actions-are-severely-limited-on-prs/18179
However there is a workaround in which we can use events on `pull_request_target` instead of `pull_request`, but this is not supported currently in `sbt-github-actions`

**Comment by amitksingh1490** [comment]
**Approach**

1. Event to be listened should be pull_request_target
2. Create a `zhttp-jar` from the fork branch commit.
3. Add jar path to `Techempower` repo's `build.sbt`.
4. Run Benchmarks.
5. Post Comment.

**Challenges**

1. Github actions restrict pull-requests from fork to do any write operation commenting is one of them, so we need to use `pull_request_target`
2. Commits from fork repository whole path is not accessible in github actions hence we need to create a jar.
3. Creating a jar causes issues in de-dupe so merge strategy needs to be defined.
4. `sbt-github-actions` don't have support for therefore need to pull_request_target write `yml` manually

**Comment by tusharmath** [comment]
May be we can disable it completely on forks. The green check from the CI is something that all contributors love :)

**Comment by amitksingh1490** [comment]
This is fixed in #820. It will skip the comment, benchmark result could be checked in the workflow logs
