### ISSUE TITLE
composing endpoints doesn't work

### ISSUE THREAD

**Issue by girdharshubham** [zio/zio-http#729]
**Describe the bug**
Combining endpoints isn't working as expected

**To Reproduce**
```scala
object Endpoints extends App {
  def h1 = GET / "a" / *[Int] / "b" / *[Boolean] to { a =>
    Response.text(a.params.toString)
  }

  def h2 = GET / "b" / *[Int] / "b" / *[Boolean] to { a =>
    Response.text(a.params.toString)
  }
  // Run it like any simple app
  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    Server.start(8091, h2 ++ h1).exitCode
}
```
```bash
GET /a/2/b/true // The requested URI "/a/2/b/true" was not found on this server
GET /b/2/b/true // (2,true)
```

**Expected behavior**
```bash
GET /a/2/b/true // (2, true)
GET /b/2/b/true // (2, true)
```

**Comment by brendo-m** [comment]
I was poking around to learn more about how zio-http works and believe I have a root cause. 

The actual routes you use are irrelevant, if the first one doesn't match it gets returned.

If a route doesn't match we end up [here](https://github.com/dream11/zio-http/blob/40c071171a5b2dabc7e148267c719f26bdbb2bd4/zio-http/src/main/scala/zhttp/endpoint/CanConstruct.scala#L46) and return a `NOT_FOUND`. But this means the [partial function in `Collect`](https://github.com/dream11/zio-http/blob/40c071171a5b2dabc7e148267c719f26bdbb2bd4/zio-http/src/main/scala/zhttp/http/Http.scala#L323) is defined, and so we end up returning `HExit.Success(NOT_FOUND)` and the [`FoldM shortcircuits`](https://github.com/dream11/zio-http/blob/40c071171a5b2dabc7e148267c719f26bdbb2bd4/zio-http/src/main/scala/zhttp/http/Http.scala#L334) and doesn't try the default.

Not sure about the cleanest way to fix this. A NOT_FOUND response should only be returned after trying all the routes, but since they are encoded inside nested `FoldM`s it's difficult to know when they've all been tried.

Side note: the default in a `FoldM` does actually get run every time, even if a route is matched. [this should be a thuink](https://github.com/dream11/zio-http/blob/40c071171a5b2dabc7e148267c719f26bdbb2bd4/zio-http/src/main/scala/zhttp/http/Http.scala#L162)
