### ISSUE TITLE
No way to determine if a request path ends with a trailing slash

### ISSUE THREAD

**Issue by adamw** [zio/zio-http#919]
**Describe the bug**
The trailing slash seems to be removed. The application can't then determine if the request URL ended with a trailing slash. If there's a redirect adding a trailing slash (so that relative references in an html page work correctly), this causes an infinite lop

**To Reproduce**
```scala
import zio._
import zhttp.http._
import zhttp.service.Server

object Test2 extends App {
  val app = Http.collect[Request] { case r => Response.text(r.url.toString) }

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    Server.start(8090, app).exitCode
}

/*
$ curl http://localhost:8090/a/b/c
URL(/a/b/c,Relative,Map(),None)

$ curl http://localhost:8090/a/b/c/
URL(/a/b/c,Relative,Map(),None)
*/
```

**Expected behavior**
I'd expect to be able to determine if there was a trailing slash in the second request.

**Desktop (please complete the following information):**
1.0.0-RC23

**Comment by girdharshubham** [comment]
Thanks for this ticket @adamw
This is being worked upon in this PR: https://github.com/dream11/zio-http/pull/846

**Comment by tusharmath** [comment]
Thanks for reporting this issue. I don't think it was ever supported in ZIO http (I could be wrong)

**Comment by tusharmath** [comment]
If that's true, then I also feel this is more of an enhancement than a bug. Because trailing slash supported is now needed in the library :)

**Comment by Dennis4b** [comment]
Is there a current status for this? (since FR #1020 is closed and some branches deleted without merge) 

For a webdav implementation the distinction between `/resource` and `/resource/` is important.

One source of inspiration, and a fairly non-invasive solution, could be the `http4s` approach of `/ "resource" / ""`, so using a trailing empty path-segment like `List("resource", "")` to indicate there was, and to match on, a trailing slash.

(Alternatively, if one doesn't need the partial matching DSL, is there another way to access the original URL/path just to see if there was a slash at the end or not?).

**Comment by desavitsky** [comment]
Hi!
Any updates on this issue?

**Comment by amitksingh1490** [comment]
https://github.com/dream11/zio-http/pull/1195/files 
I will cleanup this and merge it soon

**Comment by desavitsky** [comment]
great!

**Comment by desavitsky** [comment]
Any chance it will be released in the next RC?
